sudo: required
services:
    - docker

before_install:
    - docker build -t GBKumbhar/docker-react -f Dockerfile.dev .
    
script:
    - docker run GBKumbhar/docker-react npm run test -- --coverage
